src/Entity/Series.php
<?php

namespace App\Entity;


use Vich\Uploadable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SeriesRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[UniqueEntity('Nom')]
#[ORM\Entity(repositoryClass: SeriesRepository::class)]
#[Vich\Uploadable]
class Series
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $Nom = null;

    #[Vich\UploadableField(mapping: 'series_images', fileNameProperty: 'imageName')]
    private ?File $imagefile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column]
    #[Assert\Positive()]
    #[Assert\NotNull()]
    #[Assert\Range(
        min: 1903 ,
        max: 2023,
        notInRangeMessage: 'You must be between {{ min }}cm and {{ max }}cm tall to enter',
    )]
    private ?int $Annee = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    #[Assert\LessThan(1000)]
    private ?int $NbComics = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $Description = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $isFavorite = false;

    #[ORM\Column(type: 'boolean')]
    private $isPublic = false;


    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Comics::class)]
    private Collection $Comics;

    #[ORM\ManyToOne(inversedBy: 'Series')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'series', targetEntity: Mark::class, orphanRemoval: true)]
    private Collection $marks;

    private ?float $average = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->Comics = new ArrayCollection();
        $this->marks = new ArrayCollection();
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function setImagefile(?File $imagefile = null): void
    {
        $this->imagefile = $imagefile;

        if (null !== $imagefile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImagefile(): ?File
    {
        return $this->imagefile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getAnnee(): ?int
    {
        return $this->Annee;
    }

    public function setAnnee(int $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }

    public function getNbComics(): ?int
    {
        return $this->NbComics;
    }

    public function setNbComics(?int $NbComics): self
    {
        $this->NbComics = $NbComics;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getIsFavorite(): ?bool
    {
        return $this->isFavorite;
    }

    public function setIsFavorite(bool $isFavorite): self
    {
        $this->isFavorite = $isFavorite;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

/**
     * Get the value of updatedAt
     */ 
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the value of updatedAt
     *
     * @return  self
     */ 
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Comics>
     */
    public function getComics(): Collection
    {
        return $this->Comics;
    }

    public function addComic(Comics $comic): self
    {
        if (!$this->Comics->contains($comic)) {
            $this->Comics->add($comic);
        }

        return $this;
    }

    public function removeComic(Comics $comic): self
    {
        $this->Comics->removeElement($comic);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getMarks(): Collection
    {
        return $this->marks;
    }

    public function addMark(Mark $mark): self
    {
        if (!$this->marks->contains($mark)) {
            $this->marks->add($mark);
            $mark->setSeries($this);
        }

        return $this;
    }

    public function removeMark(Mark $mark): self
    {
        if ($this->marks->removeElement($mark)) {
            // set the owning side to null (unless already changed)
            if ($mark->getSeries() === $this) {
                $mark->setSeries(null);
            }
        }

        return $this;
    }



    /**
     * Get the value of average
     */ 
    public function getAverage()
    {
        $marks = $this->getMarks();

        if ($marks->toArray() === []) {
             $this->average = null;
             return $this->average;
        }

        $total = 0;
        $count = 0;
        foreach ($marks as $mark) {
            $total += $mark->getMark();
        }

        $this->average = $total / count($marks);

        return $this->average;
    }

    
}

src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Mark;
use App\Entity\Series;
use App\Form\MarkType;
use App\Form\SerieType;
use App\Repository\MarkRepository;
use App\Repository\SeriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Contracts\Cache\ItemInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security as ConfigurationSecurity;


class SerieController extends AbstractController
{
  /**
   * Ce controlleur montre toutes les series
   *
   * @param SeriesRepository $repository
   * @param PaginatorInterface $paginator
   * @param Request $request
   * @return Response
   */
    #[IsGranted('ROLE_USER')]
    #[Route('/series', name: 'series.index', methods: ['GET'])]
    public function index(
        SeriesRepository $repository, 
        PaginatorInterface $paginator, 
        Request $request
        ): Response
    {

        $series = $paginator->paginate(
            $repository->findBy(['user' => $this->getUser()]),
            $request->query->getInt('page', 1), 
            10 
        );

        return $this->render('pages/serie/index.html.twig', [
            'series' => $series,
        ]);
    }

     /**
     * Ce controlleur permet de voir des series publiques
     *
     * @return Response
     */
    #[Route('/series/communaute', 'serie.community', methods: ['GET'])]
    public function indexPublic(
        SeriesRepository $repository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $cache = new FilesystemAdapter();
        $data = $cache->get('series', function (ItemInterface $item) use ($repository) {
            $item->expiresAfter(15);
            return $repository->findPublicSerie(null);
        });

        $series = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('pages/serie/community.html.twig', [
            'series' => $series
        ]);
    }


    /**
     * Ce controlleur affiche un formulaire qui ajoute une serie 
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[IsGranted('ROLE_USER')]
    #[Route('/series/creation', name: 'series.new', methods: ['GET','POST'])]
    public function new(Request $request, EntityManagerInterface $manager) : Response
    {

        $series = new Series();
        $form = $this->createForm(SerieType::class, $series);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
           $series = $form->getData();
           $series->setUser($this->getUser());

           $manager->persist($series);
           $manager->flush();

           $this->addFlash(
            'success',
            'Votre serie bien été ajouté !'
 );

           return $this->redirectToRoute('series.index');
        }

        return $this->render('pages/serie/new.html.twig', [
           'form' => $form->createView()
        ]);   
    }

    /**
     * Ce controlleur permet de modifier une serie 
     *
     * @param Series $series
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Security("is_granted('ROLE_USER') and user === series.getUser()")]
    #[Route('/series/edition/{id}', 'series.edit', methods: ['GET', 'POST'])]
    public function edit( 
        Series $series, 
        Request $request, 
        EntityManagerInterface $manager 
        ) : Response
    {
        $form = $this->createForm(SerieType::class, $series);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
             $series = $form->getData();
             
             $manager->persist($series);
             $manager->flush();

             $this->addFlash(
                'success',
                'Votre serie a bien été modifiée !'
             );

            return $this->redirectToRoute('series.index');
        }

        return $this->render('pages/serie/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/series/suppression/{id}', 'series.delete', methods: ['GET'])]
    #[Security("is_granted('ROLE_USER') and user === series.getUser()")]
    
    public function delete(EntityManagerInterface $manager, Series $series) : Response 
    {

        if(!$series) {

            $this->addFlash(
                'success',
                'La serie n\'a pas été trouvé!'
             );

            return $this->redirectToRoute('series.index');
        }

        $manager->remove($series);
        $manager->flush();

        $this->addFlash(
            'success',
            'Votre serie a bien été supprimé !'
         );

        return $this->redirectToRoute('series.index');
    }

    #[ConfigurationSecurity("is_granted('ROLE_USER') and (series.getIsPublic() === true || user === series.getUser())")]
    #[Route('/series/{id}', name: 'series.show', methods: ['GET', 'POST'])]
    public function show(
        Series $series, 
        Request $request, 
        MarkRepository $markRepository,
        EntityManagerInterface $manager
        ) : Response
    {
        $mark = new Mark();
        $form = $this->createForm(MarkType::class, $mark);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $mark->setUser($this->getUser());
            $mark->setSeries($series);

            $existingMark = $markRepository->findOneBy([
                'user' => $this->getUser(),
                'series' => $series
            ]);

            if (!$existingMark) {
                $manager->persist($mark);
            }else {
                $existingMark->setMark(
                    $form->getData()->getMark()
                );
            }

            $manager->flush();

            $this->addFlash(
               'success',
                'Votre note a bien été prise en compte!'
            );

            return $this->redirectToRoute('series.show', ['id' => $series->getId()]);

        }

        return $this->render('pages/serie/show.html.twig', [
            'series' => $series,
            'form' => $form->createView()
        ]);
    }
}

templates/pages/serie/community.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComicsStorage -  Series
{% endblock %}

{% block body %}
	<div class="container mt-4">
		{% if not series is same as([])%}

			<h1>Series de la communauté</h1>

			<div class="d-flex justify-content-between flex-wrap mt-4">
				{% for serie in series %}
					<a class="card border-primary mb-3 text-decoration-none " style="max-width: 20rem;" href="http://127.0.0.1:8000/series/{{serie.id}}" role="button">
						<div class="card-header">Serie n°{{ serie.id }}</div>
						<div class="card-body">
							<h4 class="card-title">{{ serie.Nom }}</h4>
							<p class="card-text">{{ serie.description|slice(0, 100) ~ '...'  }}</p>
						</div>
					</a>
				{% endfor %}
			</div>


		{% else %}
			<h4>
				Il n'y a pas de series</h4>
		{% endif %}
	</div>
{% endblock %}

templates/pages/serie/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
Modification d'un comics - ComicsStorage
{% endblock %}

{% block body %}
<div class="container">

  <h1 class="mt-4">Modifier une serie</h1>

  

  {{form_start(form)}}
  
     {% for message in app.flashes('succes') %}
         <div class="alert alert-success mt-4">
          {{ message }}
         </div>
        {% endfor %}

  <div class="form-group">
  {{ form_row(form.imagefile) }}
         {{ form_label(form.Nom)}}
         {{ form_widget(form.Nom)}}
         <div class="form-error">
         {{ form_errors(form.Nom)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.Annee)}}
         {{ form_widget(form.Annee)}}
         <div class="form-error">
         {{ form_errors(form.Annee)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.NbComics)}}
         {{ form_widget(form.NbComics)}}
         <div class="form-error">
         {{ form_errors(form.NbComics)}}
         </div>
       </div> 

  <div class="form-group">
         {{ form_label(form.Description)}}
         {{ form_widget(form.Description)}}
         <div class="form-error">
         {{ form_errors(form.Description)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.isFavorite)}}
         {{ form_widget(form.isFavorite)}}
         <div class="form-error">
         {{ form_errors(form.isFavorite)}}
         </div>
       </div>



{{ form_row(form.Comics) }}

  <div class="form-group">
         {{ form_row(form.submit) }}
       </div>

{{ form_end(form) }}
</div>
{% endblock %}

templates/pages/serie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComicsStorage -  Series
{% endblock %}

{% block body %}
   <div class="container mt-4">
    {% if not series is same as([])%}
    
        <h1>Series</h1>

        <a href="{{ path('series.new') }}" class="btn btn-primary mt-2">
        Ajouter une serie
        </a>

         {% for message in app.flashes('success') %}
         <div class="alert alert-success mt-4">
          {{ message }}
         </div>
        {% endfor %}

    <div class="count mt-2" >
   <span >Il y a {{ series.getTotalItemCount }} series au total</span>
    </div>

    <table class="table table-hover mt-4">
     <thead>
      <tr>
       <th scope="col">Numéro</th>
       <th scope="col">Nom</th>
       <th scope="col">Année</th>
       <th scope="col">NbComics</th>
       <th scope="col">Description</th>
       <th scope="col">Date de création</th>
       <th scope="col">Edition</th>
       <th scope="col">Suppression</th>
     </tr>
    </thead>
    <tbody>
     {% for serie in series %}
      <tr class="table-dark">
       <th scope="row">{{ serie.id }}</th>
        <td>{{ serie.nom }}</td>
        <td>{{ serie.Annee }}</td>
        <td>{{ serie.nbcomics}}</td>
        <td>{{ serie.description}}</td>
        <td>{{ serie.createdAt|date("d/m/Y") }}</td>
        <td>
        <a href="{{ path('series.edit', { id: serie.id }) }}" class="btn btn-info"> Modifier</a>
        </td>
        <td>
        <a href="{{ path('series.delete', { id: serie.id }) }}" onclick="return confirm('Voulez-vous vraiment supprimer cette serie ?')" class="btn btn-warning"> Supprimer</a>
          </td>
      </tr>
     {% endfor %}
    </tbody>
    </table>

    <div class="navigation d-flex justify-content-center mt-4">
       {{ knp_pagination_render(series) }}
    </div>
    {% else %}
        <h4> Il n'y a pas de series</h4>
{% endif %}
   </div>
{% endblock %}
        

templates/pages/serie/new.html.twig
{% extends "base.html.twig" %}

{% block title %}
Ajouter une serie - ComicsStorage
{% endblock %}

{% block body %}
<div class="container">

  <h1 class="mt-4">Ajouter une serie</h1>

  

{{form_start(form)}}
  
  <div class="form-group">
         {{ form_label(form.Nom)}}
         {{ form_row(form.imagefile) }}
         {{ form_widget(form.Nom)}}
         <div class="form-error">
         {{ form_errors(form.Nom)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.Annee)}}
         {{ form_widget(form.Annee)}}
         <div class="form-error">
         {{ form_errors(form.Annee)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.NbComics)}}
         {{ form_widget(form.NbComics)}}
         <div class="form-error">
         {{ form_errors(form.NbComics)}}
         </div>
       </div> 

  <div class="form-group">
         {{ form_label(form.Description)}}
         {{ form_widget(form.Description)}}
         <div class="form-error">
         {{ form_errors(form.Description)}}
         </div>
       </div>

  <div class="form-group">
         {{ form_label(form.isFavorite)}}
         {{ form_widget(form.isFavorite)}}
         <div class="form-error">
         {{ form_errors(form.isFavorite)}}
         </div>
       </div>



{{ form_row(form.Comics) }}

  <div class="form-group">
         {{ form_row(form.submit) }}
       </div>

{{ form_end(form) }}
</div>
{% endblock %}

templates/pages/serie/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	ComicsStorage -
	{{ series.nom }}
{% endblock %}

{% block body %}
	<div class="container">

		{% for message in app.flashes('success') %}
			<div class="alert alert-success mt-4">
				{{ message }}
			</div>
		{% endfor %}

		<h1 class="mt-4">
			{{ series.nom }}
		</h1>

		<div class="series_image">
		<img style="max-width: 500px;" src="{{ vich_uploader_asset(series, 'imagefile')}}">
		</div

		<span class="badge bg-secondary">La moyenne de cette serie est de
			{{ series.average|number_format(2, '.', ',') }}/5
		</span>

		<div>
			<span class="badge bg-primary mt-2">Créée le
				{{ series.createdAt|date('d/m/Y') }}</span>
		</div>

		<p class="mt-2">Année de parution :
			{{ series.Annee }}</p>

		{% if series.NbComics %}
			<p>Nombre de comics dans la serie :
				{{ series.NbComics }}</p>
		{% else %}
			<p>Pas de comics renseigné</p>
		{% endif %}

		<div class="card border-primary mb-3 mt-4" style="max-width: 50rem;">
			<div class="card-header">Description</div>
			<div class="card-body">
				<p class="card-text">{{ series.description }}</p>
			</div>
		</div>


		<h3 class="mt-4">Comics</h3>
		{% for comic in series.Comics %}
			<span class="badge bg-dark">{{ comic.nom }}</span>
		{% endfor %}

		<div>
			{{ form(form) }}
			</div>


		</div>

	{% endblock %}