src/Entity/Comics.php
<?php

namespace App\Entity;

use App\Repository\ComicsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComicsRepository::class)]
#[UniqueEntity('Nom')]
class Comics
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $Nom = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    #[Assert\LessThan(200)]
    private ?float $Prix = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'Comics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Form/ComicsType.php
<?php

namespace App\Form;

use App\Entity\Comics;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Validator\Constraints as Assert;
use Webmozart\Assert\Assert as AssertAssert;

class ComicsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => '2',
                    'maxlength' => '50',

                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' =>2, 'max' => 50]),
                    new Assert\NotBlank()
                ]
            ])
            ->add('Prix', MoneyType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Prix',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Positive(),
                    new Assert\NotNull(),
                    new Assert\LessThan(200),
                ]
            ])
            
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary mt-4',
                ],
                'label' => 'Ajouter mon comics'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comics::class,
        ]);
    }
}

src/Controller/ComicsController.php
<?php

namespace App\Controller;

use App\Entity\Comics;
use App\Form\ComicsType;
use Doctrine\ORM\EntityManager;
use App\Repository\ComicsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ComicsController extends AbstractController
{
    /**
     * Ce controlleur montre tous les comics 
     * 
     * @param ComicsRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    #[Route('/comics', name: 'app_comics', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function index(ComicsRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {

        $comics = $paginator->paginate(
            $repository->findBy(['user' => $this->getUser()]),
            $request->query->getInt('page', 1), 
            10 
        );

        return $this->render('pages/comics/index.html.twig', [
            'comics' => $comics
        ]);
    }

    /**
     * Ce controlleur montre un formulaire qui créer un comics
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('comics/nouveau', 'comics.new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(
        Request $request,
        EntityManagerInterface $manager
    ): Response {

        $comics = new Comics();
        $form = $this->createForm(ComicsType::class, $comics);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
             $comics = $form->getData();
             $comics->setUser($this->getUser());
             
             $manager->persist($comics);
             $manager->flush();

             $this->addFlash(
                'success',
                'Votre comics a bien été ajouté !'
             );

            return $this->redirectToRoute('app_comics');
        }

        return $this->render('pages/comics/new.html.twig',[
            'form' => $form->createview()
        ]);
    }

    
    /**
     * Ce controlleur premet de modifier un comics 
     *
     * @param Comics $comics
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */ 
    #[Security("is_granted('ROLE_USER') and user === comics.getUser()")]
    #[Route('/comics/edition/{id}', 'comics.edit', methods: ['GET', 'POST'])]
    public function edit( 
        Comics $comics, 
        Request $request, 
        EntityManagerInterface $manager 
        ) : Response
    {
        $form = $this->createForm(ComicsType::class, $comics);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
             $comics = $form->getData();
             
             $manager->persist($comics);
             $manager->flush();

             $this->addFlash(
                'success',
                'Votre comics a bien été modifié !'
             );

            return $this->redirectToRoute('app_comics');
        }

        return $this->render('pages/comics/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    
    #[Route('/comics/suppression/{id}', 'comics.delete', methods: ['GET'])]
    #[Security("is_granted('ROLE_USER') and user === comics.getUser()")]
    /**
     * Ce controlleur permet de supprimer un comics 
     *
     * @param EntityManagerInterface $manager
     * @param Comics $comics
     * @return Response
     */
    public function delete(EntityManagerInterface $manager, Comics $comics) : Response 
    {

        if(!$comics) {

            $this->addFlash(
                'success',
                'Le comics n\'a pas été trouvé!'
             );

            return $this->redirectToRoute('app_comics');
        }

        $manager->remove($comics);
        $manager->flush();

        $this->addFlash(
            'success',
            'Votre comics a bien été supprimé !'
         );

        return $this->redirectToRoute('app_comics');
    }

}

templates/pages/comics/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
Modification d'un comics - ComicsStorage
{% endblock %}

{% block body %}
<div class="container">

  <h1 class="mt-4">Modifier un comics</h1>

  {{ form_start(form) }}
    
       <div class="form-group">
         {{ form_label(form.Nom)}}
         {{ form_widget(form.Nom)}}
         <div class="form-error">
         {{ form_errors(form.Nom)}}
         </div>
       </div>

       <div class="form-group">
         {{ form_label(form.Prix)}}
         {{ form_widget(form.Prix)}}
         <div class="form-error">
         {{ form_errors(form.Prix)}}
         </div>
       </div>

       <div class="form-group">
         {{ form_row(form.submit) }}
       </div>

{{ form_end(form) }}
</div>
{% endblock %}

templates/pages/comics/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComicsStorage -  Mes Comics
{% endblock %}

{% block body %}
   <div class="container mt-4">
    {% if not comics is same as([])%}
    
        <h1>Mes Comics</h1>

        <a href="{{ path('comics.new') }}" class="btn btn-primary mt-2">
        Ajouter un comics
        </a>

        {% for message in app.flashes('success') %}
         <div class="alert alert-success mt-4">
          {{ message }}
         </div>
        {% endfor %}

    <div class="count mt-2" >
   <span >Il y a {{ comics.getTotalItemCount }} comics au total</span>
    </div>

    <table class="table table-hover mt-4">
     <thead>
      <tr>
       <th scope="col">Numéro</th>
       <th scope="col">Nom</th>
       <th scope="col">Prix</th>
       <th scope="col">Date de création</th>
       <th scope="col">Edition</th>
       <th scope="col">Suppression</th>
     </tr>
    </thead>
    <tbody>
     {% for comic in comics %}
      <tr class="table-dark">
       <th scope="row">{{ comic.id }}</th>
        <td>{{ comic.nom }}</td>
        <td>{{ comic.prix|number_format(2, '.', ',') }} €</td>
        <td>{{ comic.createdAt|date("d/m/Y") }}</td>
        <td>
         <a href="{{ path('comics.edit', { id: comic.id }) }}" class="btn btn-info"> Modifier</a>
        </td>
        <td>
        <a href="{{ path('comics.delete', { id: comic.id }) }}" onclick="return confirm('Voulez-vous vraiment supprimer ce comics ?')" class="btn btn-warning"> Supprimer</a>
        </td>
      </tr>
     {% endfor %}
    </tbody>
    </table>

    <div class="navigation d-flex justify-content-center mt-4">
       {{ knp_pagination_render(comics) }}
    </div>
    {% else %}
        <h4> Il n'y a pas de comics </h4>
{% endif %}
   </div>
{% endblock %}

templates/pages/comics/new.html.twig
{% extends "base.html.twig" %}

{% block title %}
Ajouter un comics - ComicsStorage
{% endblock %}

{% block body %}
<div class="container">

  <h1 class="mt-4">Ajouter un comics</h1>

  {{ form_start(form) }}
    
       <div class="form-group">
         {{ form_label(form.Nom)}}
         {{ form_widget(form.Nom)}}
         <div class="form-error">
         {{ form_errors(form.Nom)}}
         </div>
       </div>

       <div class="form-group">
         {{ form_label(form.Prix)}}
         {{ form_widget(form.Prix)}}
         <div class="form-error">
         {{ form_errors(form.Prix)}}
         </div>
       </div>

       <div class="form-group">
         {{ form_row(form._token) }}
       </div>

       <div class="form-group">
         {{ form_row(form.submit) }}
       </div>

{{ form_end(form) }}
</div>
{% endblock %}